server:
  port: 8085


spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html

  servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 100MB


  thymeleaf:
    cache: false

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


# biz config
# windows system should config like D:\\data\\complex
py.file.savePath: C:\\Users\\83632\\Desktop\\data\\complex
py.file.readFilePath: C:\\Users\\83632\\Desktop\\data\\complex\\py\\Model_Predict.py